module.exports = {
  // accessibility: true,
  // adaptiveHeight: false,
  // autoplay: false,
  // autoplaySpeed: 3000,
  // arrows: true,
  // asNavFor: null,
  // appendArrows: $(element),
  // appendDots: $(element),
  prevArrow: '<button type="button" class="slick-prev mediaSlider-prevButton">←</button>',
  nextArrow: '<button type="button" class="slick-next mediaSlider-nextButton">→</button>',
  // centerMode: false,
  // centerPadding: '50px',
  // cssEase: 'ease',
  // customPaging: null,
  dots: true,
  // dotsClass: 'slick-dots',
  // draggable: true,
  // fade: false,
  // focusOnSelect: false,
  // easing: 'linear',
  // edgeFriction: 0.15,
  infinite: false
  // initialSlide: 0,
  // lazyLoad: 'ondemand',
  // mobileFirst: false,
  // pauseOnFocus: true,
  // pauseOnHover: true,
  // pauseOnDotsHover: false,
  // respondTo: 'window',
  // responsive: null,
  // rows: 1,
  // slide: '',
  // slidesPerRow: 1,
  // slidesToShow: 1,
  // slidesToScroll: 1,
  // speed: 300,
  // swipe: true,
  // swipeToSlide: false,
  // touchMove: true,
  // touchThreshold: 5,
  // useCSS: true,
  // useTransform: true,
  // variableWidth: false,
  // vertical: false,
  // verticalSwiping: false,
  // rtl: false,
  // waitForAnimate: true,
  // zIndex: 1000
}
