<?php

namespace Flynt\Components\BlockCountUp;

use Flynt\Api;

Api::registerFields('BlockCountUp', [
    'layout' => [
        'name' => 'BlockCountUp',
        'label' => 'Block: Count Up',
        'sub_fields' => [
            [
                'label' => '',
                'name' => 'options',
                'type' => 'group',
                'layout' => 'row',
                'sub_fields' => [
                    [
                        'label' => 'Theme',
                        'name' => 'theme',
                        'type' => 'select',
                        'allow_null' => 0,
                        'multiple' => 0,
                        'ui' => 0,
                        'ajax' => 0,
                        'choices' => [
                            '' => 'Default',
                            'themeLight' => 'Light',
                            'themeDark' => 'Dark',
                            'themeHero' => 'Hero'
                        ]
                    ]
                ]
            ],
            [
                'label' => 'Pre Content HTML',
                'name' => 'preContentHtml',
                'type' => 'wysiwyg',
                'tabs' => 'visual,text',
                'toolbar' => 'full',
                'media_upload' => 0,
                'delay' => 1
            ],
            [
                'label' => 'Items',
                'name' => 'items',
                'type' => 'repeater',
                'min' => 1,
                'max' => 4,
                'layout' => 'row',
                'button_label' => 'Add Item',
                'sub_fields' => [
                    [
                        'label' => 'Icon',
                        'name' => 'icon',
                        'type' => 'select',
                        'allow_null' => 1,
                        'multiple' => 0,
                        'ui' => 1,
                        'ajax' => 0,
                        'choices' => [
                            'activity' => '<i style="width: 16px; height: 16px; vertical-align: middle; position: relative; top: -2px;margin-right: 5px" data-feather="activity"></i> activity',
                            'airplay' => '<i style="width: 16px; height: 16px; vertical-align: middle; position: relative; top: -2px;margin-right: 5px" data-feather="airplay"></i> airplay',
                            'alert-circle' => '<i style="width: 16px; height: 16px; vertical-align: middle; position: relative; top: -2px;margin-right: 5px" data-feather="alert-circle"></i> alert-circle',
                            'alert-octagon' => '<i style="width: 16px; height: 16px; vertical-align: middle; position: relative; top: -2px;margin-right: 5px" data-feather="alert-octagon"></i> alert-octagon',
                            'alert-triangle' => '<i style="width: 16px; height: 16px; vertical-align: middle; position: relative; top: -2px;margin-right: 5px" data-feather="alert-triangle"></i> alert-triangle',
                            'align-center' => '<i style="width: 16px; height: 16px; vertical-align: middle; position: relative; top: -2px;margin-right: 5px" data-feather="align-center"></i> align-center',
                            'align-justify' => '<i style="width: 16px; height: 16px; vertical-align: middle; position: relative; top: -2px;margin-right: 5px" data-feather="align-justify"></i> align-justify',
                            'align-left' => '<i style="width: 16px; height: 16px; vertical-align: middle; position: relative; top: -2px;margin-right: 5px" data-feather="align-left"></i> align-left',
                            'align-right' => '<i style="width: 16px; height: 16px; vertical-align: middle; position: relative; top: -2px;margin-right: 5px" data-feather="align-right"></i> align-right',
                            'anchor' => '<i style="width: 16px; height: 16px; vertical-align: middle; position: relative; top: -2px;margin-right: 5px" data-feather="anchor"></i> anchor',
                            'aperture' => '<i style="width: 16px; height: 16px; vertical-align: middle; position: relative; top: -2px;margin-right: 5px" data-feather="aperture"></i> aperture',
                            'archive' => '<i style="width: 16px; height: 16px; vertical-align: middle; position: relative; top: -2px;margin-right: 5px" data-feather="archive"></i> archive',
                            'arrow-down-circle' => '<i style="width: 16px; height: 16px; vertical-align: middle; position: relative; top: -2px;margin-right: 5px" data-feather="arrow-down-circle"></i> arrow-down-circle',
                            'arrow-down-left' => '<i style="width: 16px; height: 16px; vertical-align: middle; position: relative; top: -2px;margin-right: 5px" data-feather="arrow-down-left"></i> arrow-down-left',
                            'arrow-down-right' => '<i style="width: 16px; height: 16px; vertical-align: middle; position: relative; top: -2px;margin-right: 5px" data-feather="arrow-down-right"></i> arrow-down-right',
                            'arrow-down' => '<i style="width: 16px; height: 16px; vertical-align: middle; position: relative; top: -2px;margin-right: 5px" data-feather="arrow-down"></i> arrow-down',
                            'arrow-left-circle' => '<i style="width: 16px; height: 16px; vertical-align: middle; position: relative; top: -2px;margin-right: 5px" data-feather="arrow-left-circle"></i> arrow-left-circle',
                            'arrow-left' => '<i style="width: 16px; height: 16px; vertical-align: middle; position: relative; top: -2px;margin-right: 5px" data-feather="arrow-left"></i> arrow-left',
                            'arrow-right-circle' => '<i style="width: 16px; height: 16px; vertical-align: middle; position: relative; top: -2px;margin-right: 5px" data-feather="arrow-right-circle"></i> arrow-right-circle',
                            'arrow-right' => '<i style="width: 16px; height: 16px; vertical-align: middle; position: relative; top: -2px;margin-right: 5px" data-feather="arrow-right"></i> arrow-right',
                            'arrow-up-circle' => '<i style="width: 16px; height: 16px; vertical-align: middle; position: relative; top: -2px;margin-right: 5px" data-feather="arrow-up-circle"></i> arrow-up-circle',
                            'arrow-up-left' => '<i style="width: 16px; height: 16px; vertical-align: middle; position: relative; top: -2px;margin-right: 5px" data-feather="arrow-up-left"></i> arrow-up-left',
                            'arrow-up-right' => '<i style="width: 16px; height: 16px; vertical-align: middle; position: relative; top: -2px;margin-right: 5px" data-feather="arrow-up-right"></i> arrow-up-right',
                            'arrow-up' => '<i style="width: 16px; height: 16px; vertical-align: middle; position: relative; top: -2px;margin-right: 5px" data-feather="arrow-up"></i> arrow-up',
                            'at-sign' => '<i style="width: 16px; height: 16px; vertical-align: middle; position: relative; top: -2px;margin-right: 5px" data-feather="at-sign"></i> at-sign',
                            'award' => '<i style="width: 16px; height: 16px; vertical-align: middle; position: relative; top: -2px;margin-right: 5px" data-feather="award"></i> award',
                            'bar-chart-2' => '<i style="width: 16px; height: 16px; vertical-align: middle; position: relative; top: -2px;margin-right: 5px" data-feather="bar-chart-2"></i> bar-chart-2',
                            'bar-chart' => '<i style="width: 16px; height: 16px; vertical-align: middle; position: relative; top: -2px;margin-right: 5px" data-feather="bar-chart"></i> bar-chart',
                            'battery-charging' => '<i style="width: 16px; height: 16px; vertical-align: middle; position: relative; top: -2px;margin-right: 5px" data-feather="battery-charging"></i> battery-charging',
                            'battery' => '<i style="width: 16px; height: 16px; vertical-align: middle; position: relative; top: -2px;margin-right: 5px" data-feather="battery"></i> battery',
                            'bell-off' => '<i style="width: 16px; height: 16px; vertical-align: middle; position: relative; top: -2px;margin-right: 5px" data-feather="bell-off"></i> bell-off',
                            'bell' => '<i style="width: 16px; height: 16px; vertical-align: middle; position: relative; top: -2px;margin-right: 5px" data-feather="bell"></i> bell',
                            'bluetooth' => '<i style="width: 16px; height: 16px; vertical-align: middle; position: relative; top: -2px;margin-right: 5px" data-feather="bluetooth"></i> bluetooth',
                            'bold' => '<i style="width: 16px; height: 16px; vertical-align: middle; position: relative; top: -2px;margin-right: 5px" data-feather="bold"></i> bold',
                            'book-open' => '<i style="width: 16px; height: 16px; vertical-align: middle; position: relative; top: -2px;margin-right: 5px" data-feather="book-open"></i> book-open',
                            'book' => '<i style="width: 16px; height: 16px; vertical-align: middle; position: relative; top: -2px;margin-right: 5px" data-feather="book"></i> book',
                            'bookmark' => '<i style="width: 16px; height: 16px; vertical-align: middle; position: relative; top: -2px;margin-right: 5px" data-feather="bookmark"></i> bookmark',
                            'box' => '<i style="width: 16px; height: 16px; vertical-align: middle; position: relative; top: -2px;margin-right: 5px" data-feather="box"></i> box',
                            'briefcase' => '<i style="width: 16px; height: 16px; vertical-align: middle; position: relative; top: -2px;margin-right: 5px" data-feather="briefcase"></i> briefcase',
                            'calendar' => '<i style="width: 16px; height: 16px; vertical-align: middle; position: relative; top: -2px;margin-right: 5px" data-feather="calendar"></i> calendar',
                            'camera-off' => '<i style="width: 16px; height: 16px; vertical-align: middle; position: relative; top: -2px;margin-right: 5px" data-feather="camera-off"></i> camera-off',
                            'camera' => '<i style="width: 16px; height: 16px; vertical-align: middle; position: relative; top: -2px;margin-right: 5px" data-feather="camera"></i> camera',
                            'cast' => '<i style="width: 16px; height: 16px; vertical-align: middle; position: relative; top: -2px;margin-right: 5px" data-feather="cast"></i> cast',
                            'check-circle' => '<i style="width: 16px; height: 16px; vertical-align: middle; position: relative; top: -2px;margin-right: 5px" data-feather="check-circle"></i> check-circle',
                            'check-square' => '<i style="width: 16px; height: 16px; vertical-align: middle; position: relative; top: -2px;margin-right: 5px" data-feather="check-square"></i> check-square',
                            'check' => '<i style="width: 16px; height: 16px; vertical-align: middle; position: relative; top: -2px;margin-right: 5px" data-feather="check"></i> check',
                            'chevron-down' => '<i style="width: 16px; height: 16px; vertical-align: middle; position: relative; top: -2px;margin-right: 5px" data-feather="chevron-down"></i> chevron-down',
                            'chevron-left' => '<i style="width: 16px; height: 16px; vertical-align: middle; position: relative; top: -2px;margin-right: 5px" data-feather="chevron-left"></i> chevron-left',
                            'chevron-right' => '<i style="width: 16px; height: 16px; vertical-align: middle; position: relative; top: -2px;margin-right: 5px" data-feather="chevron-right"></i> chevron-right',
                            'chevron-up' => '<i style="width: 16px; height: 16px; vertical-align: middle; position: relative; top: -2px;margin-right: 5px" data-feather="chevron-up"></i> chevron-up',
                            'chevrons-down' => '<i style="width: 16px; height: 16px; vertical-align: middle; position: relative; top: -2px;margin-right: 5px" data-feather="chevrons-down"></i> chevrons-down',
                            'chevrons-left' => '<i style="width: 16px; height: 16px; vertical-align: middle; position: relative; top: -2px;margin-right: 5px" data-feather="chevrons-left"></i> chevrons-left',
                            'chevrons-right' => '<i style="width: 16px; height: 16px; vertical-align: middle; position: relative; top: -2px;margin-right: 5px" data-feather="chevrons-right"></i> chevrons-right',
                            'chevrons-up' => '<i style="width: 16px; height: 16px; vertical-align: middle; position: relative; top: -2px;margin-right: 5px" data-feather="chevrons-up"></i> chevrons-up',
                            'chrome' => '<i style="width: 16px; height: 16px; vertical-align: middle; position: relative; top: -2px;margin-right: 5px" data-feather="chrome"></i> chrome',
                            'circle' => '<i style="width: 16px; height: 16px; vertical-align: middle; position: relative; top: -2px;margin-right: 5px" data-feather="circle"></i> circle',
                            'clipboard' => '<i style="width: 16px; height: 16px; vertical-align: middle; position: relative; top: -2px;margin-right: 5px" data-feather="clipboard"></i> clipboard',
                            'clock' => '<i style="width: 16px; height: 16px; vertical-align: middle; position: relative; top: -2px;margin-right: 5px" data-feather="clock"></i> clock',
                            'cloud-drizzle' => '<i style="width: 16px; height: 16px; vertical-align: middle; position: relative; top: -2px;margin-right: 5px" data-feather="cloud-drizzle"></i> cloud-drizzle',
                            'cloud-lightning' => '<i style="width: 16px; height: 16px; vertical-align: middle; position: relative; top: -2px;margin-right: 5px" data-feather="cloud-lightning"></i> cloud-lightning',
                            'cloud-off' => '<i style="width: 16px; height: 16px; vertical-align: middle; position: relative; top: -2px;margin-right: 5px" data-feather="cloud-off"></i> cloud-off',
                            'cloud-rain' => '<i style="width: 16px; height: 16px; vertical-align: middle; position: relative; top: -2px;margin-right: 5px" data-feather="cloud-rain"></i> cloud-rain',
                            'cloud-snow' => '<i style="width: 16px; height: 16px; vertical-align: middle; position: relative; top: -2px;margin-right: 5px" data-feather="cloud-snow"></i> cloud-snow',
                            'cloud' => '<i style="width: 16px; height: 16px; vertical-align: middle; position: relative; top: -2px;margin-right: 5px" data-feather="cloud"></i> cloud',
                            'code' => '<i style="width: 16px; height: 16px; vertical-align: middle; position: relative; top: -2px;margin-right: 5px" data-feather="code"></i> code',
                            'codepen' => '<i style="width: 16px; height: 16px; vertical-align: middle; position: relative; top: -2px;margin-right: 5px" data-feather="codepen"></i> codepen',
                            'codesandbox' => '<i style="width: 16px; height: 16px; vertical-align: middle; position: relative; top: -2px;margin-right: 5px" data-feather="codesandbox"></i> codesandbox',
                            'coffee' => '<i style="width: 16px; height: 16px; vertical-align: middle; position: relative; top: -2px;margin-right: 5px" data-feather="coffee"></i> coffee',
                            'columns' => '<i style="width: 16px; height: 16px; vertical-align: middle; position: relative; top: -2px;margin-right: 5px" data-feather="columns"></i> columns',
                            'command' => '<i style="width: 16px; height: 16px; vertical-align: middle; position: relative; top: -2px;margin-right: 5px" data-feather="command"></i> command',
                            'compass' => '<i style="width: 16px; height: 16px; vertical-align: middle; position: relative; top: -2px;margin-right: 5px" data-feather="compass"></i> compass',
                            'copy' => '<i style="width: 16px; height: 16px; vertical-align: middle; position: relative; top: -2px;margin-right: 5px" data-feather="copy"></i> copy',
                            'corner-down-left' => '<i style="width: 16px; height: 16px; vertical-align: middle; position: relative; top: -2px;margin-right: 5px" data-feather="corner-down-left"></i> corner-down-left',
                            'corner-down-right' => '<i style="width: 16px; height: 16px; vertical-align: middle; position: relative; top: -2px;margin-right: 5px" data-feather="corner-down-right"></i> corner-down-right',
                            'corner-left-down' => '<i style="width: 16px; height: 16px; vertical-align: middle; position: relative; top: -2px;margin-right: 5px" data-feather="corner-left-down"></i> corner-left-down',
                            'corner-left-up' => '<i style="width: 16px; height: 16px; vertical-align: middle; position: relative; top: -2px;margin-right: 5px" data-feather="corner-left-up"></i> corner-left-up',
                            'corner-right-down' => '<i style="width: 16px; height: 16px; vertical-align: middle; position: relative; top: -2px;margin-right: 5px" data-feather="corner-right-down"></i> corner-right-down',
                            'corner-right-up' => '<i style="width: 16px; height: 16px; vertical-align: middle; position: relative; top: -2px;margin-right: 5px" data-feather="corner-right-up"></i> corner-right-up',
                            'corner-up-left' => '<i style="width: 16px; height: 16px; vertical-align: middle; position: relative; top: -2px;margin-right: 5px" data-feather="corner-up-left"></i> corner-up-left',
                            'corner-up-right' => '<i style="width: 16px; height: 16px; vertical-align: middle; position: relative; top: -2px;margin-right: 5px" data-feather="corner-up-right"></i> corner-up-right',
                            'cpu' => '<i style="width: 16px; height: 16px; vertical-align: middle; position: relative; top: -2px;margin-right: 5px" data-feather="cpu"></i> cpu',
                            'credit-card' => '<i style="width: 16px; height: 16px; vertical-align: middle; position: relative; top: -2px;margin-right: 5px" data-feather="credit-card"></i> credit-card',
                            'crop' => '<i style="width: 16px; height: 16px; vertical-align: middle; position: relative; top: -2px;margin-right: 5px" data-feather="crop"></i> crop',
                            'crosshair' => '<i style="width: 16px; height: 16px; vertical-align: middle; position: relative; top: -2px;margin-right: 5px" data-feather="crosshair"></i> crosshair',
                            'database' => '<i style="width: 16px; height: 16px; vertical-align: middle; position: relative; top: -2px;margin-right: 5px" data-feather="database"></i> database',
                            'delete' => '<i style="width: 16px; height: 16px; vertical-align: middle; position: relative; top: -2px;margin-right: 5px" data-feather="delete"></i> delete',
                            'disc' => '<i style="width: 16px; height: 16px; vertical-align: middle; position: relative; top: -2px;margin-right: 5px" data-feather="disc"></i> disc',
                            'dollar-sign' => '<i style="width: 16px; height: 16px; vertical-align: middle; position: relative; top: -2px;margin-right: 5px" data-feather="dollar-sign"></i> dollar-sign',
                            'download-cloud' => '<i style="width: 16px; height: 16px; vertical-align: middle; position: relative; top: -2px;margin-right: 5px" data-feather="download-cloud"></i> download-cloud',
                            'download' => '<i style="width: 16px; height: 16px; vertical-align: middle; position: relative; top: -2px;margin-right: 5px" data-feather="download"></i> download',
                            'droplet' => '<i style="width: 16px; height: 16px; vertical-align: middle; position: relative; top: -2px;margin-right: 5px" data-feather="droplet"></i> droplet',
                            'edit-2' => '<i style="width: 16px; height: 16px; vertical-align: middle; position: relative; top: -2px;margin-right: 5px" data-feather="edit-2"></i> edit-2',
                            'edit-3' => '<i style="width: 16px; height: 16px; vertical-align: middle; position: relative; top: -2px;margin-right: 5px" data-feather="edit-3"></i> edit-3',
                            'edit' => '<i style="width: 16px; height: 16px; vertical-align: middle; position: relative; top: -2px;margin-right: 5px" data-feather="edit"></i> edit',
                            'external-link' => '<i style="width: 16px; height: 16px; vertical-align: middle; position: relative; top: -2px;margin-right: 5px" data-feather="external-link"></i> external-link',
                            'eye-off' => '<i style="width: 16px; height: 16px; vertical-align: middle; position: relative; top: -2px;margin-right: 5px" data-feather="eye-off"></i> eye-off',
                            'eye' => '<i style="width: 16px; height: 16px; vertical-align: middle; position: relative; top: -2px;margin-right: 5px" data-feather="eye"></i> eye',
                            'facebook' => '<i style="width: 16px; height: 16px; vertical-align: middle; position: relative; top: -2px;margin-right: 5px" data-feather="facebook"></i> facebook',
                            'fast-forward' => '<i style="width: 16px; height: 16px; vertical-align: middle; position: relative; top: -2px;margin-right: 5px" data-feather="fast-forward"></i> fast-forward',
                            'feather' => '<i style="width: 16px; height: 16px; vertical-align: middle; position: relative; top: -2px;margin-right: 5px" data-feather="feather"></i> feather',
                            'figma' => '<i style="width: 16px; height: 16px; vertical-align: middle; position: relative; top: -2px;margin-right: 5px" data-feather="figma"></i> figma',
                            'file-minus' => '<i style="width: 16px; height: 16px; vertical-align: middle; position: relative; top: -2px;margin-right: 5px" data-feather="file-minus"></i> file-minus',
                            'file-plus' => '<i style="width: 16px; height: 16px; vertical-align: middle; position: relative; top: -2px;margin-right: 5px" data-feather="file-plus"></i> file-plus',
                            'file-text' => '<i style="width: 16px; height: 16px; vertical-align: middle; position: relative; top: -2px;margin-right: 5px" data-feather="file-text"></i> file-text',
                            'file' => '<i style="width: 16px; height: 16px; vertical-align: middle; position: relative; top: -2px;margin-right: 5px" data-feather="file"></i> file',
                            'film' => '<i style="width: 16px; height: 16px; vertical-align: middle; position: relative; top: -2px;margin-right: 5px" data-feather="film"></i> film',
                            'filter' => '<i style="width: 16px; height: 16px; vertical-align: middle; position: relative; top: -2px;margin-right: 5px" data-feather="filter"></i> filter',
                            'flag' => '<i style="width: 16px; height: 16px; vertical-align: middle; position: relative; top: -2px;margin-right: 5px" data-feather="flag"></i> flag',
                            'folder-minus' => '<i style="width: 16px; height: 16px; vertical-align: middle; position: relative; top: -2px;margin-right: 5px" data-feather="folder-minus"></i> folder-minus',
                            'folder-plus' => '<i style="width: 16px; height: 16px; vertical-align: middle; position: relative; top: -2px;margin-right: 5px" data-feather="folder-plus"></i> folder-plus',
                            'folder' => '<i style="width: 16px; height: 16px; vertical-align: middle; position: relative; top: -2px;margin-right: 5px" data-feather="folder"></i> folder',
                            'framer' => '<i style="width: 16px; height: 16px; vertical-align: middle; position: relative; top: -2px;margin-right: 5px" data-feather="framer"></i> framer',
                            'frown' => '<i style="width: 16px; height: 16px; vertical-align: middle; position: relative; top: -2px;margin-right: 5px" data-feather="frown"></i> frown',
                            'gift' => '<i style="width: 16px; height: 16px; vertical-align: middle; position: relative; top: -2px;margin-right: 5px" data-feather="gift"></i> gift',
                            'git-branch' => '<i style="width: 16px; height: 16px; vertical-align: middle; position: relative; top: -2px;margin-right: 5px" data-feather="git-branch"></i> git-branch',
                            'git-commit' => '<i style="width: 16px; height: 16px; vertical-align: middle; position: relative; top: -2px;margin-right: 5px" data-feather="git-commit"></i> git-commit',
                            'git-merge' => '<i style="width: 16px; height: 16px; vertical-align: middle; position: relative; top: -2px;margin-right: 5px" data-feather="git-merge"></i> git-merge',
                            'git-pull-request' => '<i style="width: 16px; height: 16px; vertical-align: middle; position: relative; top: -2px;margin-right: 5px" data-feather="git-pull-request"></i> git-pull-request',
                            'github' => '<i style="width: 16px; height: 16px; vertical-align: middle; position: relative; top: -2px;margin-right: 5px" data-feather="github"></i> github',
                            'gitlab' => '<i style="width: 16px; height: 16px; vertical-align: middle; position: relative; top: -2px;margin-right: 5px" data-feather="gitlab"></i> gitlab',
                            'globe' => '<i style="width: 16px; height: 16px; vertical-align: middle; position: relative; top: -2px;margin-right: 5px" data-feather="globe"></i> globe',
                            'grid' => '<i style="width: 16px; height: 16px; vertical-align: middle; position: relative; top: -2px;margin-right: 5px" data-feather="grid"></i> grid',
                            'hard-drive' => '<i style="width: 16px; height: 16px; vertical-align: middle; position: relative; top: -2px;margin-right: 5px" data-feather="hard-drive"></i> hard-drive',
                            'hash' => '<i style="width: 16px; height: 16px; vertical-align: middle; position: relative; top: -2px;margin-right: 5px" data-feather="hash"></i> hash',
                            'headphones' => '<i style="width: 16px; height: 16px; vertical-align: middle; position: relative; top: -2px;margin-right: 5px" data-feather="headphones"></i> headphones',
                            'heart' => '<i style="width: 16px; height: 16px; vertical-align: middle; position: relative; top: -2px;margin-right: 5px" data-feather="heart"></i> heart',
                            'help-circle' => '<i style="width: 16px; height: 16px; vertical-align: middle; position: relative; top: -2px;margin-right: 5px" data-feather="help-circle"></i> help-circle',
                            'hexagon' => '<i style="width: 16px; height: 16px; vertical-align: middle; position: relative; top: -2px;margin-right: 5px" data-feather="hexagon"></i> hexagon',
                            'home' => '<i style="width: 16px; height: 16px; vertical-align: middle; position: relative; top: -2px;margin-right: 5px" data-feather="home"></i> home',
                            'image' => '<i style="width: 16px; height: 16px; vertical-align: middle; position: relative; top: -2px;margin-right: 5px" data-feather="image"></i> image',
                            'inbox' => '<i style="width: 16px; height: 16px; vertical-align: middle; position: relative; top: -2px;margin-right: 5px" data-feather="inbox"></i> inbox',
                            'info' => '<i style="width: 16px; height: 16px; vertical-align: middle; position: relative; top: -2px;margin-right: 5px" data-feather="info"></i> info',
                            'instagram' => '<i style="width: 16px; height: 16px; vertical-align: middle; position: relative; top: -2px;margin-right: 5px" data-feather="instagram"></i> instagram',
                            'italic' => '<i style="width: 16px; height: 16px; vertical-align: middle; position: relative; top: -2px;margin-right: 5px" data-feather="italic"></i> italic',
                            'key' => '<i style="width: 16px; height: 16px; vertical-align: middle; position: relative; top: -2px;margin-right: 5px" data-feather="key"></i> key',
                            'layers' => '<i style="width: 16px; height: 16px; vertical-align: middle; position: relative; top: -2px;margin-right: 5px" data-feather="layers"></i> layers',
                            'layout' => '<i style="width: 16px; height: 16px; vertical-align: middle; position: relative; top: -2px;margin-right: 5px" data-feather="layout"></i> layout',
                            'life-buoy' => '<i style="width: 16px; height: 16px; vertical-align: middle; position: relative; top: -2px;margin-right: 5px" data-feather="life-buoy"></i> life-buoy',
                            'link-2' => '<i style="width: 16px; height: 16px; vertical-align: middle; position: relative; top: -2px;margin-right: 5px" data-feather="link-2"></i> link-2',
                            'link' => '<i style="width: 16px; height: 16px; vertical-align: middle; position: relative; top: -2px;margin-right: 5px" data-feather="link"></i> link',
                            'linkedin' => '<i style="width: 16px; height: 16px; vertical-align: middle; position: relative; top: -2px;margin-right: 5px" data-feather="linkedin"></i> linkedin',
                            'list' => '<i style="width: 16px; height: 16px; vertical-align: middle; position: relative; top: -2px;margin-right: 5px" data-feather="list"></i> list',
                            'loader' => '<i style="width: 16px; height: 16px; vertical-align: middle; position: relative; top: -2px;margin-right: 5px" data-feather="loader"></i> loader',
                            'lock' => '<i style="width: 16px; height: 16px; vertical-align: middle; position: relative; top: -2px;margin-right: 5px" data-feather="lock"></i> lock',
                            'log-in' => '<i style="width: 16px; height: 16px; vertical-align: middle; position: relative; top: -2px;margin-right: 5px" data-feather="log-in"></i> log-in',
                            'log-out' => '<i style="width: 16px; height: 16px; vertical-align: middle; position: relative; top: -2px;margin-right: 5px" data-feather="log-out"></i> log-out',
                            'mail' => '<i style="width: 16px; height: 16px; vertical-align: middle; position: relative; top: -2px;margin-right: 5px" data-feather="mail"></i> mail',
                            'map-pin' => '<i style="width: 16px; height: 16px; vertical-align: middle; position: relative; top: -2px;margin-right: 5px" data-feather="map-pin"></i> map-pin',
                            'map' => '<i style="width: 16px; height: 16px; vertical-align: middle; position: relative; top: -2px;margin-right: 5px" data-feather="map"></i> map',
                            'maximize-2' => '<i style="width: 16px; height: 16px; vertical-align: middle; position: relative; top: -2px;margin-right: 5px" data-feather="maximize-2"></i> maximize-2',
                            'maximize' => '<i style="width: 16px; height: 16px; vertical-align: middle; position: relative; top: -2px;margin-right: 5px" data-feather="maximize"></i> maximize',
                            'meh' => '<i style="width: 16px; height: 16px; vertical-align: middle; position: relative; top: -2px;margin-right: 5px" data-feather="meh"></i> meh',
                            'menu' => '<i style="width: 16px; height: 16px; vertical-align: middle; position: relative; top: -2px;margin-right: 5px" data-feather="menu"></i> menu',
                            'message-circle' => '<i style="width: 16px; height: 16px; vertical-align: middle; position: relative; top: -2px;margin-right: 5px" data-feather="message-circle"></i> message-circle',
                            'message-square' => '<i style="width: 16px; height: 16px; vertical-align: middle; position: relative; top: -2px;margin-right: 5px" data-feather="message-square"></i> message-square',
                            'mic-off' => '<i style="width: 16px; height: 16px; vertical-align: middle; position: relative; top: -2px;margin-right: 5px" data-feather="mic-off"></i> mic-off',
                            'mic' => '<i style="width: 16px; height: 16px; vertical-align: middle; position: relative; top: -2px;margin-right: 5px" data-feather="mic"></i> mic',
                            'minimize-2' => '<i style="width: 16px; height: 16px; vertical-align: middle; position: relative; top: -2px;margin-right: 5px" data-feather="minimize-2"></i> minimize-2',
                            'minimize' => '<i style="width: 16px; height: 16px; vertical-align: middle; position: relative; top: -2px;margin-right: 5px" data-feather="minimize"></i> minimize',
                            'minus-circle' => '<i style="width: 16px; height: 16px; vertical-align: middle; position: relative; top: -2px;margin-right: 5px" data-feather="minus-circle"></i> minus-circle',
                            'minus-square' => '<i style="width: 16px; height: 16px; vertical-align: middle; position: relative; top: -2px;margin-right: 5px" data-feather="minus-square"></i> minus-square',
                            'minus' => '<i style="width: 16px; height: 16px; vertical-align: middle; position: relative; top: -2px;margin-right: 5px" data-feather="minus"></i> minus',
                            'monitor' => '<i style="width: 16px; height: 16px; vertical-align: middle; position: relative; top: -2px;margin-right: 5px" data-feather="monitor"></i> monitor',
                            'moon' => '<i style="width: 16px; height: 16px; vertical-align: middle; position: relative; top: -2px;margin-right: 5px" data-feather="moon"></i> moon',
                            'more-horizontal' => '<i style="width: 16px; height: 16px; vertical-align: middle; position: relative; top: -2px;margin-right: 5px" data-feather="more-horizontal"></i> more-horizontal',
                            'more-vertical' => '<i style="width: 16px; height: 16px; vertical-align: middle; position: relative; top: -2px;margin-right: 5px" data-feather="more-vertical"></i> more-vertical',
                            'mouse-pointer' => '<i style="width: 16px; height: 16px; vertical-align: middle; position: relative; top: -2px;margin-right: 5px" data-feather="mouse-pointer"></i> mouse-pointer',
                            'move' => '<i style="width: 16px; height: 16px; vertical-align: middle; position: relative; top: -2px;margin-right: 5px" data-feather="move"></i> move',
                            'music' => '<i style="width: 16px; height: 16px; vertical-align: middle; position: relative; top: -2px;margin-right: 5px" data-feather="music"></i> music',
                            'navigation-2' => '<i style="width: 16px; height: 16px; vertical-align: middle; position: relative; top: -2px;margin-right: 5px" data-feather="navigation-2"></i> navigation-2',
                            'navigation' => '<i style="width: 16px; height: 16px; vertical-align: middle; position: relative; top: -2px;margin-right: 5px" data-feather="navigation"></i> navigation',
                            'octagon' => '<i style="width: 16px; height: 16px; vertical-align: middle; position: relative; top: -2px;margin-right: 5px" data-feather="octagon"></i> octagon',
                            'package' => '<i style="width: 16px; height: 16px; vertical-align: middle; position: relative; top: -2px;margin-right: 5px" data-feather="package"></i> package',
                            'paperclip' => '<i style="width: 16px; height: 16px; vertical-align: middle; position: relative; top: -2px;margin-right: 5px" data-feather="paperclip"></i> paperclip',
                            'pause-circle' => '<i style="width: 16px; height: 16px; vertical-align: middle; position: relative; top: -2px;margin-right: 5px" data-feather="pause-circle"></i> pause-circle',
                            'pause' => '<i style="width: 16px; height: 16px; vertical-align: middle; position: relative; top: -2px;margin-right: 5px" data-feather="pause"></i> pause',
                            'pen-tool' => '<i style="width: 16px; height: 16px; vertical-align: middle; position: relative; top: -2px;margin-right: 5px" data-feather="pen-tool"></i> pen-tool',
                            'percent' => '<i style="width: 16px; height: 16px; vertical-align: middle; position: relative; top: -2px;margin-right: 5px" data-feather="percent"></i> percent',
                            'phone-call' => '<i style="width: 16px; height: 16px; vertical-align: middle; position: relative; top: -2px;margin-right: 5px" data-feather="phone-call"></i> phone-call',
                            'phone-forwarded' => '<i style="width: 16px; height: 16px; vertical-align: middle; position: relative; top: -2px;margin-right: 5px" data-feather="phone-forwarded"></i> phone-forwarded',
                            'phone-incoming' => '<i style="width: 16px; height: 16px; vertical-align: middle; position: relative; top: -2px;margin-right: 5px" data-feather="phone-incoming"></i> phone-incoming',
                            'phone-missed' => '<i style="width: 16px; height: 16px; vertical-align: middle; position: relative; top: -2px;margin-right: 5px" data-feather="phone-missed"></i> phone-missed',
                            'phone-off' => '<i style="width: 16px; height: 16px; vertical-align: middle; position: relative; top: -2px;margin-right: 5px" data-feather="phone-off"></i> phone-off',
                            'phone-outgoing' => '<i style="width: 16px; height: 16px; vertical-align: middle; position: relative; top: -2px;margin-right: 5px" data-feather="phone-outgoing"></i> phone-outgoing',
                            'phone' => '<i style="width: 16px; height: 16px; vertical-align: middle; position: relative; top: -2px;margin-right: 5px" data-feather="phone"></i> phone',
                            'pie-chart' => '<i style="width: 16px; height: 16px; vertical-align: middle; position: relative; top: -2px;margin-right: 5px" data-feather="pie-chart"></i> pie-chart',
                            'play-circle' => '<i style="width: 16px; height: 16px; vertical-align: middle; position: relative; top: -2px;margin-right: 5px" data-feather="play-circle"></i> play-circle',
                            'play' => '<i style="width: 16px; height: 16px; vertical-align: middle; position: relative; top: -2px;margin-right: 5px" data-feather="play"></i> play',
                            'plus-circle' => '<i style="width: 16px; height: 16px; vertical-align: middle; position: relative; top: -2px;margin-right: 5px" data-feather="plus-circle"></i> plus-circle',
                            'plus-square' => '<i style="width: 16px; height: 16px; vertical-align: middle; position: relative; top: -2px;margin-right: 5px" data-feather="plus-square"></i> plus-square',
                            'plus' => '<i style="width: 16px; height: 16px; vertical-align: middle; position: relative; top: -2px;margin-right: 5px" data-feather="plus"></i> plus',
                            'pocket' => '<i style="width: 16px; height: 16px; vertical-align: middle; position: relative; top: -2px;margin-right: 5px" data-feather="pocket"></i> pocket',
                            'power' => '<i style="width: 16px; height: 16px; vertical-align: middle; position: relative; top: -2px;margin-right: 5px" data-feather="power"></i> power',
                            'printer' => '<i style="width: 16px; height: 16px; vertical-align: middle; position: relative; top: -2px;margin-right: 5px" data-feather="printer"></i> printer',
                            'radio' => '<i style="width: 16px; height: 16px; vertical-align: middle; position: relative; top: -2px;margin-right: 5px" data-feather="radio"></i> radio',
                            'refresh-ccw' => '<i style="width: 16px; height: 16px; vertical-align: middle; position: relative; top: -2px;margin-right: 5px" data-feather="refresh-ccw"></i> refresh-ccw',
                            'refresh-cw' => '<i style="width: 16px; height: 16px; vertical-align: middle; position: relative; top: -2px;margin-right: 5px" data-feather="refresh-cw"></i> refresh-cw',
                            'repeat' => '<i style="width: 16px; height: 16px; vertical-align: middle; position: relative; top: -2px;margin-right: 5px" data-feather="repeat"></i> repeat',
                            'rewind' => '<i style="width: 16px; height: 16px; vertical-align: middle; position: relative; top: -2px;margin-right: 5px" data-feather="rewind"></i> rewind',
                            'rotate-ccw' => '<i style="width: 16px; height: 16px; vertical-align: middle; position: relative; top: -2px;margin-right: 5px" data-feather="rotate-ccw"></i> rotate-ccw',
                            'rotate-cw' => '<i style="width: 16px; height: 16px; vertical-align: middle; position: relative; top: -2px;margin-right: 5px" data-feather="rotate-cw"></i> rotate-cw',
                            'rss' => '<i style="width: 16px; height: 16px; vertical-align: middle; position: relative; top: -2px;margin-right: 5px" data-feather="rss"></i> rss',
                            'save' => '<i style="width: 16px; height: 16px; vertical-align: middle; position: relative; top: -2px;margin-right: 5px" data-feather="save"></i> save',
                            'scissors' => '<i style="width: 16px; height: 16px; vertical-align: middle; position: relative; top: -2px;margin-right: 5px" data-feather="scissors"></i> scissors',
                            'search' => '<i style="width: 16px; height: 16px; vertical-align: middle; position: relative; top: -2px;margin-right: 5px" data-feather="search"></i> search',
                            'send' => '<i style="width: 16px; height: 16px; vertical-align: middle; position: relative; top: -2px;margin-right: 5px" data-feather="send"></i> send',
                            'server' => '<i style="width: 16px; height: 16px; vertical-align: middle; position: relative; top: -2px;margin-right: 5px" data-feather="server"></i> server',
                            'settings' => '<i style="width: 16px; height: 16px; vertical-align: middle; position: relative; top: -2px;margin-right: 5px" data-feather="settings"></i> settings',
                            'share-2' => '<i style="width: 16px; height: 16px; vertical-align: middle; position: relative; top: -2px;margin-right: 5px" data-feather="share-2"></i> share-2',
                            'share' => '<i style="width: 16px; height: 16px; vertical-align: middle; position: relative; top: -2px;margin-right: 5px" data-feather="share"></i> share',
                            'shield-off' => '<i style="width: 16px; height: 16px; vertical-align: middle; position: relative; top: -2px;margin-right: 5px" data-feather="shield-off"></i> shield-off',
                            'shield' => '<i style="width: 16px; height: 16px; vertical-align: middle; position: relative; top: -2px;margin-right: 5px" data-feather="shield"></i> shield',
                            'shopping-bag' => '<i style="width: 16px; height: 16px; vertical-align: middle; position: relative; top: -2px;margin-right: 5px" data-feather="shopping-bag"></i> shopping-bag',
                            'shopping-cart' => '<i style="width: 16px; height: 16px; vertical-align: middle; position: relative; top: -2px;margin-right: 5px" data-feather="shopping-cart"></i> shopping-cart',
                            'shuffle' => '<i style="width: 16px; height: 16px; vertical-align: middle; position: relative; top: -2px;margin-right: 5px" data-feather="shuffle"></i> shuffle',
                            'sidebar' => '<i style="width: 16px; height: 16px; vertical-align: middle; position: relative; top: -2px;margin-right: 5px" data-feather="sidebar"></i> sidebar',
                            'skip-back' => '<i style="width: 16px; height: 16px; vertical-align: middle; position: relative; top: -2px;margin-right: 5px" data-feather="skip-back"></i> skip-back',
                            'skip-forward' => '<i style="width: 16px; height: 16px; vertical-align: middle; position: relative; top: -2px;margin-right: 5px" data-feather="skip-forward"></i> skip-forward',
                            'slack' => '<i style="width: 16px; height: 16px; vertical-align: middle; position: relative; top: -2px;margin-right: 5px" data-feather="slack"></i> slack',
                            'slash' => '<i style="width: 16px; height: 16px; vertical-align: middle; position: relative; top: -2px;margin-right: 5px" data-feather="slash"></i> slash',
                            'sliders' => '<i style="width: 16px; height: 16px; vertical-align: middle; position: relative; top: -2px;margin-right: 5px" data-feather="sliders"></i> sliders',
                            'smartphone' => '<i style="width: 16px; height: 16px; vertical-align: middle; position: relative; top: -2px;margin-right: 5px" data-feather="smartphone"></i> smartphone',
                            'smile' => '<i style="width: 16px; height: 16px; vertical-align: middle; position: relative; top: -2px;margin-right: 5px" data-feather="smile"></i> smile',
                            'speaker' => '<i style="width: 16px; height: 16px; vertical-align: middle; position: relative; top: -2px;margin-right: 5px" data-feather="speaker"></i> speaker',
                            'square' => '<i style="width: 16px; height: 16px; vertical-align: middle; position: relative; top: -2px;margin-right: 5px" data-feather="square"></i> square',
                            'star' => '<i style="width: 16px; height: 16px; vertical-align: middle; position: relative; top: -2px;margin-right: 5px" data-feather="star"></i> star',
                            'stop-circle' => '<i style="width: 16px; height: 16px; vertical-align: middle; position: relative; top: -2px;margin-right: 5px" data-feather="stop-circle"></i> stop-circle',
                            'sun' => '<i style="width: 16px; height: 16px; vertical-align: middle; position: relative; top: -2px;margin-right: 5px" data-feather="sun"></i> sun',
                            'sunrise' => '<i style="width: 16px; height: 16px; vertical-align: middle; position: relative; top: -2px;margin-right: 5px" data-feather="sunrise"></i> sunrise',
                            'sunset' => '<i style="width: 16px; height: 16px; vertical-align: middle; position: relative; top: -2px;margin-right: 5px" data-feather="sunset"></i> sunset',
                            'tablet' => '<i style="width: 16px; height: 16px; vertical-align: middle; position: relative; top: -2px;margin-right: 5px" data-feather="tablet"></i> tablet',
                            'tag' => '<i style="width: 16px; height: 16px; vertical-align: middle; position: relative; top: -2px;margin-right: 5px" data-feather="tag"></i> tag',
                            'target' => '<i style="width: 16px; height: 16px; vertical-align: middle; position: relative; top: -2px;margin-right: 5px" data-feather="target"></i> target',
                            'terminal' => '<i style="width: 16px; height: 16px; vertical-align: middle; position: relative; top: -2px;margin-right: 5px" data-feather="terminal"></i> terminal',
                            'thermometer' => '<i style="width: 16px; height: 16px; vertical-align: middle; position: relative; top: -2px;margin-right: 5px" data-feather="thermometer"></i> thermometer',
                            'thumbs-down' => '<i style="width: 16px; height: 16px; vertical-align: middle; position: relative; top: -2px;margin-right: 5px" data-feather="thumbs-down"></i> thumbs-down',
                            'thumbs-up' => '<i style="width: 16px; height: 16px; vertical-align: middle; position: relative; top: -2px;margin-right: 5px" data-feather="thumbs-up"></i> thumbs-up',
                            'toggle-left' => '<i style="width: 16px; height: 16px; vertical-align: middle; position: relative; top: -2px;margin-right: 5px" data-feather="toggle-left"></i> toggle-left',
                            'toggle-right' => '<i style="width: 16px; height: 16px; vertical-align: middle; position: relative; top: -2px;margin-right: 5px" data-feather="toggle-right"></i> toggle-right',
                            'trash-2' => '<i style="width: 16px; height: 16px; vertical-align: middle; position: relative; top: -2px;margin-right: 5px" data-feather="trash-2"></i> trash-2',
                            'trash' => '<i style="width: 16px; height: 16px; vertical-align: middle; position: relative; top: -2px;margin-right: 5px" data-feather="trash"></i> trash',
                            'trello' => '<i style="width: 16px; height: 16px; vertical-align: middle; position: relative; top: -2px;margin-right: 5px" data-feather="trello"></i> trello',
                            'trending-down' => '<i style="width: 16px; height: 16px; vertical-align: middle; position: relative; top: -2px;margin-right: 5px" data-feather="trending-down"></i> trending-down',
                            'trending-up' => '<i style="width: 16px; height: 16px; vertical-align: middle; position: relative; top: -2px;margin-right: 5px" data-feather="trending-up"></i> trending-up',
                            'triangle' => '<i style="width: 16px; height: 16px; vertical-align: middle; position: relative; top: -2px;margin-right: 5px" data-feather="triangle"></i> triangle',
                            'truck' => '<i style="width: 16px; height: 16px; vertical-align: middle; position: relative; top: -2px;margin-right: 5px" data-feather="truck"></i> truck',
                            'tv' => '<i style="width: 16px; height: 16px; vertical-align: middle; position: relative; top: -2px;margin-right: 5px" data-feather="tv"></i> tv',
                            'twitter' => '<i style="width: 16px; height: 16px; vertical-align: middle; position: relative; top: -2px;margin-right: 5px" data-feather="twitter"></i> twitter',
                            'type' => '<i style="width: 16px; height: 16px; vertical-align: middle; position: relative; top: -2px;margin-right: 5px" data-feather="type"></i> type',
                            'umbrella' => '<i style="width: 16px; height: 16px; vertical-align: middle; position: relative; top: -2px;margin-right: 5px" data-feather="umbrella"></i> umbrella',
                            'underline' => '<i style="width: 16px; height: 16px; vertical-align: middle; position: relative; top: -2px;margin-right: 5px" data-feather="underline"></i> underline',
                            'unlock' => '<i style="width: 16px; height: 16px; vertical-align: middle; position: relative; top: -2px;margin-right: 5px" data-feather="unlock"></i> unlock',
                            'upload-cloud' => '<i style="width: 16px; height: 16px; vertical-align: middle; position: relative; top: -2px;margin-right: 5px" data-feather="upload-cloud"></i> upload-cloud',
                            'upload' => '<i style="width: 16px; height: 16px; vertical-align: middle; position: relative; top: -2px;margin-right: 5px" data-feather="upload"></i> upload',
                            'user-check' => '<i style="width: 16px; height: 16px; vertical-align: middle; position: relative; top: -2px;margin-right: 5px" data-feather="user-check"></i> user-check',
                            'user-minus' => '<i style="width: 16px; height: 16px; vertical-align: middle; position: relative; top: -2px;margin-right: 5px" data-feather="user-minus"></i> user-minus',
                            'user-plus' => '<i style="width: 16px; height: 16px; vertical-align: middle; position: relative; top: -2px;margin-right: 5px" data-feather="user-plus"></i> user-plus',
                            'user-x' => '<i style="width: 16px; height: 16px; vertical-align: middle; position: relative; top: -2px;margin-right: 5px" data-feather="user-x"></i> user-x',
                            'user' => '<i style="width: 16px; height: 16px; vertical-align: middle; position: relative; top: -2px;margin-right: 5px" data-feather="user"></i> user',
                            'users' => '<i style="width: 16px; height: 16px; vertical-align: middle; position: relative; top: -2px;margin-right: 5px" data-feather="users"></i> users',
                            'video-off' => '<i style="width: 16px; height: 16px; vertical-align: middle; position: relative; top: -2px;margin-right: 5px" data-feather="video-off"></i> video-off',
                            'video' => '<i style="width: 16px; height: 16px; vertical-align: middle; position: relative; top: -2px;margin-right: 5px" data-feather="video"></i> video',
                            'voicemail' => '<i style="width: 16px; height: 16px; vertical-align: middle; position: relative; top: -2px;margin-right: 5px" data-feather="voicemail"></i> voicemail',
                            'volume-1' => '<i style="width: 16px; height: 16px; vertical-align: middle; position: relative; top: -2px;margin-right: 5px" data-feather="volume-1"></i> volume-1',
                            'volume-2' => '<i style="width: 16px; height: 16px; vertical-align: middle; position: relative; top: -2px;margin-right: 5px" data-feather="volume-2"></i> volume-2',
                            'volume-x' => '<i style="width: 16px; height: 16px; vertical-align: middle; position: relative; top: -2px;margin-right: 5px" data-feather="volume-x"></i> volume-x',
                            'volume' => '<i style="width: 16px; height: 16px; vertical-align: middle; position: relative; top: -2px;margin-right: 5px" data-feather="volume"></i> volume',
                            'watch' => '<i style="width: 16px; height: 16px; vertical-align: middle; position: relative; top: -2px;margin-right: 5px" data-feather="watch"></i> watch',
                            'wifi-off' => '<i style="width: 16px; height: 16px; vertical-align: middle; position: relative; top: -2px;margin-right: 5px" data-feather="wifi-off"></i> wifi-off',
                            'wifi' => '<i style="width: 16px; height: 16px; vertical-align: middle; position: relative; top: -2px;margin-right: 5px" data-feather="wifi"></i> wifi',
                            'wind' => '<i style="width: 16px; height: 16px; vertical-align: middle; position: relative; top: -2px;margin-right: 5px" data-feather="wind"></i> wind',
                            'x-circle' => '<i style="width: 16px; height: 16px; vertical-align: middle; position: relative; top: -2px;margin-right: 5px" data-feather="x-circle"></i> x-circle',
                            'x-octagon' => '<i style="width: 16px; height: 16px; vertical-align: middle; position: relative; top: -2px;margin-right: 5px" data-feather="x-octagon"></i> x-octagon',
                            'x-square' => '<i style="width: 16px; height: 16px; vertical-align: middle; position: relative; top: -2px;margin-right: 5px" data-feather="x-square"></i> x-square',
                            'x' => '<i style="width: 16px; height: 16px; vertical-align: middle; position: relative; top: -2px;margin-right: 5px" data-feather="x"></i> x',
                            'youtube' => '<i style="width: 16px; height: 16px; vertical-align: middle; position: relative; top: -2px;margin-right: 5px" data-feather="youtube"></i> youtube',
                            'zap-off' => '<i style="width: 16px; height: 16px; vertical-align: middle; position: relative; top: -2px;margin-right: 5px" data-feather="zap-off"></i> zap-off',
                            'zap' => '<i style="width: 16px; height: 16px; vertical-align: middle; position: relative; top: -2px;margin-right: 5px" data-feather="zap"></i> zap',
                            'zoom-in' => '<i style="width: 16px; height: 16px; vertical-align: middle; position: relative; top: -2px;margin-right: 5px" data-feather="zoom-in"></i> zoom-in',
                            'zoom-out' => '<i style="width: 16px; height: 16px; vertical-align: middle; position: relative; top: -2px;margin-right: 5px" data-feather="zoom-out"></i> zoom-out'
                        ],
                        'default_value' => ''
                    ],
                    [
                        'label' => 'Count Value',
                        'name' => 'numberGroup',
                        'type' => 'group',
                        'layout' => 'table',
                        'sub_fields' => [
                            [
                                'label' => 'Prefix',
                                'name' => 'numberPrefix',
                                'type' => 'text'
                            ],
                            [
                                'label' => 'Number',
                                'name' => 'number',
                                'type' => 'number',
                                'required' => 1
                            ],
                            [
                                'label' => 'Suffix',
                                'name' => 'numberSuffix',
                                'type' => 'text'
                            ]
                        ]
                    ],
                    [
                        'label' => 'Subtitle',
                        'name' => 'subtitle',
                        'type' => 'text'
                    ],
                ]
            ],
        ]
    ]
]);
